apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage
  namespace: backstage
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs
  resources: 
    requests:
      storage: 1Gi
