apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: imyashkale/backstage:v1.8
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: debug
          ports:
            - name: http
              containerPort: 7007
          envFrom:  
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
